import { Router, Response } from 'express';
import { AuthRequest, authMiddleware } from '../middleware/auth';
import { generateEndpointDocs, generateTests, generateRequest, explainError, generateCollectionReadme } from '../services/aiService';
import { z } from 'zod';
import { ApiResponse } from '../utils/response';
import { logErrorReport } from '../utils/logger';
import { ERROR_CODES } from '../constants/errorCodes';
import { catchAsync } from '../utils/catchAsync';

const SERVICE_NAME = 'AIService';
const router = Router();

router.post('/generate-docs', authMiddleware, catchAsync(async (req: AuthRequest, res: Response) => {
    try {
        const schema = z.object({
            method: z.string(),
            url: z.string(),
            body: z.any().optional(),
            response: z.any().optional(),
            userCommand: z.string().optional(),
        });

        const input = schema.parse(req.body);
        const result = await generateEndpointDocs(
            input.method,
            input.url,
            input.body,
            input.response,
            input.userCommand
        );
        res.json(ApiResponse.success({
            message: 'Documentation generated by AI',
            data: result,
        }));
    } catch (error: any) {
        logErrorReport('generateDocs', SERVICE_NAME, error, ERROR_CODES.AI_GENERATE_FAILED);
        res.status(400).json(ApiResponse.error({ message: 'AI generation failed' }));
    }
}));

router.post('/generate-tests', authMiddleware, catchAsync(async (req: AuthRequest, res: Response) => {
    try {
        const schema = z.object({
            method: z.string(),
            url: z.string(),
            response: z.any(),
        });

        const input = schema.parse(req.body);
        const result = await generateTests(input.method, input.url, input.response);
        res.json(ApiResponse.success({
            message: 'Tests generated by AI',
            data: result,
        }));
    } catch (error: any) {
        logErrorReport('generateTests', SERVICE_NAME, error, ERROR_CODES.AI_GENERATE_FAILED);
        res.status(400).json(ApiResponse.error({ message: 'AI test generation failed' }));
    }
}));

router.post('/generate-request', authMiddleware, catchAsync(async (req: AuthRequest, res: Response) => {
    try {
        const schema = z.object({
            prompt: z.string(),
        });

        const input = schema.parse(req.body);
        const result = await generateRequest(input.prompt);
        res.json(ApiResponse.success({
            message: 'Request generated by AI',
            data: result,
        }));
    } catch (error: any) {
        logErrorReport('generateRequest', SERVICE_NAME, error, ERROR_CODES.AI_GENERATE_FAILED);
        res.status(400).json(ApiResponse.error({ message: 'AI request generation failed' }));
    }
}));

router.post('/explain-error', authMiddleware, catchAsync(async (req: AuthRequest, res: Response) => {
    try {
        const schema = z.object({
            method: z.string(),
            url: z.string(),
            error: z.any(),
        });

        const input = schema.parse(req.body);
        const result = await explainError(input.url, input.method, input.error);
        res.json(ApiResponse.success({
            message: 'Error explained by AI',
            data: result,
        }));
    } catch (error: any) {
        logErrorReport('explainError', SERVICE_NAME, error, ERROR_CODES.AI_GENERATE_FAILED);
        res.status(400).json(ApiResponse.error({ message: 'AI error explanation failed' }));
    }
}));

router.post('/generate-readme', authMiddleware, catchAsync(async (req: AuthRequest, res: Response) => {
    try {
        const schema = z.object({
            title: z.string(),
            endpoints: z.array(z.any()),
        });

        const input = schema.parse(req.body);
        const result = await generateCollectionReadme(input.title, input.endpoints);
        res.json(ApiResponse.success({
            message: 'README generated by AI',
            data: result,
        }));
    } catch (error: any) {
        logErrorReport('generateReadme', SERVICE_NAME, error, ERROR_CODES.AI_GENERATE_FAILED);
        res.status(400).json(ApiResponse.error({ message: 'AI README generation failed' }));
    }
}));

export default router;
