import { Router, Response } from 'express';
import { AuthRequest, authMiddleware } from '../middleware/auth';
import { generateEndpointDocs } from '../services/aiService';
import { z } from 'zod';
import { ApiResponse } from '../utils/response';
import { logErrorReport } from '../utils/logger';
import { ERROR_CODES } from '../constants/errorCodes';

const SERVICE_NAME = 'AIService';
const router = Router();

router.post('/generate-docs', authMiddleware, async (req: AuthRequest, res: Response) => {
    try {
        const schema = z.object({
            method: z.string(),
            url: z.string(),
            body: z.any().optional(),
            response: z.any().optional(),
            userCommand: z.string().optional(),
        });

        const input = schema.parse(req.body);
        const result = await generateEndpointDocs(
            input.method,
            input.url,
            input.body,
            input.response,
            input.userCommand
        );
        res.json(ApiResponse.success({
            message: 'Documentation generated by AI',
            data: result,
        }));
    } catch (error: any) {
        logErrorReport('generateDocs', SERVICE_NAME, error, ERROR_CODES.AI_GENERATE_FAILED);
        res.status(400).json(ApiResponse.error({ message: 'AI generation failed' }));
    }
});

export default router;
