// ============================================
// Error Code Constants
// Key-value pairs for structured error tracking
// ============================================

export const ERROR_CODES = {
    // Auth
    AUTH_REGISTER_FAILED: 'AUTH_001',
    AUTH_LOGIN_FAILED: 'AUTH_002',
    AUTH_PROFILE_FETCH_FAILED: 'AUTH_003',
    AUTH_PROFILE_UPDATE_FAILED: 'AUTH_004',
    AUTH_PASSWORD_RESET_FAILED: 'AUTH_005',

    // Documentation
    DOC_LIST_FAILED: 'DOC_001',
    DOC_CREATE_FAILED: 'DOC_002',
    DOC_CREATE_EMPTY_FAILED: 'DOC_003',
    DOC_DELETE_FAILED: 'DOC_004',
    DOC_TOGGLE_PUBLIC_FAILED: 'DOC_005',
    DOC_UPDATE_FAILED: 'DOC_006',
    DOC_REQUEST_UPDATE_FAILED: 'DOC_007',
    DOC_REQUEST_DELETE_FAILED: 'DOC_008',
    DOC_REORDER_FAILED: 'DOC_009',
    DOC_REQUEST_CREATE_FAILED: 'DOC_010',
    DOC_FETCH_FAILED: 'DOC_011',
    DOC_SNIPPETS_FAILED: 'DOC_012',
    DOC_PUBLIC_FETCH_FAILED: 'DOC_013',
    DOC_SLUG_UPDATE_FAILED: 'DOC_014',

    // Environments
    ENV_FETCH_FAILED: 'ENV_001',
    ENV_CREATE_FAILED: 'ENV_002',
    ENV_UPDATE_FAILED: 'ENV_003',
    ENV_DELETE_FAILED: 'ENV_004',
    ENV_SET_ACTIVE_FAILED: 'ENV_005',

    // Folders
    FOLDER_FETCH_FAILED: 'FLD_001',
    FOLDER_CREATE_FAILED: 'FLD_002',
    FOLDER_UPDATE_FAILED: 'FLD_003',
    FOLDER_DELETE_FAILED: 'FLD_004',
    FOLDER_MOVE_REQUEST_FAILED: 'FLD_005',
    FOLDER_REORDER_FAILED: 'FLD_006',

    // Notes
    NOTE_FETCH_FAILED: 'NOTE_001',
    NOTE_FETCH_SINGLE_FAILED: 'NOTE_002',
    NOTE_CREATE_FAILED: 'NOTE_003',
    NOTE_UPDATE_FAILED: 'NOTE_004',
    NOTE_DELETE_FAILED: 'NOTE_005',
    NOTE_PIN_FAILED: 'NOTE_006',
    NOTE_TRASH_FETCH_FAILED: 'NOTE_007',
    NOTE_RESTORE_FAILED: 'NOTE_008',

    // Todos
    TODO_FETCH_FAILED: 'TODO_001',
    TODO_CREATE_FAILED: 'TODO_002',
    TODO_UPDATE_FAILED: 'TODO_003',
    TODO_DELETE_FAILED: 'TODO_004',
    TODO_REORDER_FAILED: 'TODO_005',
    TODO_TRASH_FETCH_FAILED: 'TODO_006',
    TODO_RESTORE_FAILED: 'TODO_007',

    // AI
    AI_GENERATE_FAILED: 'AI_001',

    // Collaboration
    COLLAB_INVITE_FAILED: 'CLB_001',
    COLLAB_ACCEPT_FAILED: 'CLB_002',
    COLLAB_CANCEL_FAILED: 'CLB_003',
    COLLAB_REMOVE_FAILED: 'CLB_004',
    COLLAB_UPDATE_ROLE_FAILED: 'CLB_005',
    COLLAB_FETCH_FAILED: 'CLB_006',

    // Admin
    ADMIN_TEMPLATE_FETCH_FAILED: 'ADM_001',
    ADMIN_TEMPLATE_CREATE_FAILED: 'ADM_002',
    ADMIN_TEMPLATE_UPDATE_FAILED: 'ADM_003',
    ADMIN_TEMPLATE_DELETE_FAILED: 'ADM_004',
    ADMIN_LOGS_FETCH_FAILED: 'ADM_005',
} as const;

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];
